# Generated by Django 5.1.4 on 2024-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
    ]
