# Generated by Django 5.1.4 on 2024-12-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0002_post_description_en_post_description_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_like",
                to="web_app.post",
            ),
        ),
    ]
